### PR TITLE
Add bzip2

### PR DESCRIPTION
**Pull request by asl**
This adds static libbz2 to the set of the libraries

### CODE REVIEW

**Comment by asl** [comment]
Well, IMO libbz2 is as standard as zlib :) And the compilation & installation is even easier than of zlib as no configuration is necessary

**Comment by FooBarWidget** [comment]
I think libbz is a whole lot less standard and popular than zlib though. Nowadays you still see a lot of gz files, but not very many bz2 files. Even lzma/7z/xz seems more popular.

I politely disagree.

**Comment by FooBarWidget** [comment]
Hello @asl, in the absence of further comments, I will close this issue. If this presents an unresolvable issue for you, please let me know and we can search for a different alternative.

**Comment by asl** [comment]
Well, we will simply maintain this in our fork, thanks!

**Comment by FooBarWidget** [comment]
You don't have to fork though: you can use our image as base image, and then install libbz in your Dockerfile. That's easier than forking.

**Comment by asl** [comment]
Well, it is much easier to fork. This way we could use GH packages to store the final image with additional libraries installed. And it's a bit easier to do everything in fork as there are already actions, etc. setup to build & check everything.

**Pull request closed without merging**
